### ISSUE TITLE
lnurl needs a way to work on the web

### ISSUE THREAD

**Issue by fiatjaf** [btcontract/lnurl-rfc#1]
If your wallet is in your phone or watch, scanning a QR code and doing something with the `lnurl` is ok. But what if your wallet is running in your desktop or laptop? `lnurl` must be clickable, and it must redirect to the proper your computer somehow knows is capable of handling lightning stuff.

This isn't a big problem, but here's an issue for further reference.

**Comment by btcontract** [comment]
Probably can be prefixed with `lightning:` when not embedded in a payment request?

**Comment by btcontract** [comment]
Added this to spec.
