### ISSUE TITLE
LUD-10: missing examples

### ISSUE THREAD

**Issue by robbiehanson** [btcontract/lnurl-rfc#113]
[LUD-10](https://github.com/fiatjaf/lnurl-rfc/blob/luds/10.md) doesn't clearly state what the expected structure of the decrypted content should look like. But it does say:

> For `message`, a toaster or popup is sufficient. For `url`, the wallet should give the user a popup which displays `description`, `url`, and a 'open' button to open the `url` in a new browser tab.

From this, I infer that the decrypted content should be a proper `successAction` JSON object. For example, the cleartext could be:

```json
{
  "tag": "message",
  "message": "Speakeasy passphrase: The duck quacks at daybreak."
}
```

However, in the example code, the cleartext is just the string: "Secret data".

Can we specify the expected structure of the cleartext ? And can we provide examples for `message` and `url` ?

**Comment by fiatjaf** [comment]
Sorry for the confusion. The decrypted content must be a string. Added that to the text.
