### ISSUE TITLE
LNURL for pull payments

### ISSUE THREAD

**Issue by joostjager** [btcontract/lnurl-rfc#126]
I am looking for a way to implement the following flow with LNURL:

Suppose the merchant is a video streaming service that charges monthly. A user browses around on the merchant's website and decides to sign up.

* Merchant displays a QR code to the user to sign up.
* User scans this QR code and is prompted by their wallet to authorize the merchant to push invoices. User approves and sends a callback url to the merchant.
* Each month, the merchant pushes an invoice to the user via that callback url.
* The user's wallet will notify the user so that the user can confirm payment of the pushed invoice.

An extension to this is that the user can instruct their wallet to auto-pay invoices from that merchant up to a certain limit. The limit can be hinted in the initial merchant QR code too, so that approval of push invoices and approval of the (hinted) limit can be done in a single action.

The flow contains elements of LNURL-withdraw, but isn't quite the same. I don't think the initial merchant request to push invoices via a QR code is covered already.

Any thoughts on this?

**Comment by fiatjaf** [comment]
My thoughts are that we shouldn't push on anything that requires the user to have an always-on remotely accessible server. That could be an optional increment, but the essence of the protocol should be implementable by wallets like https://lightning-wallet.com/ and https://blixtwallet.com/. We always assume the `SERVICE` has a domain and an HTTP server, but not the `WALLET` side.

Aside from that, your suggestion seems to be covered by https://github.com/fiatjaf/lnurl-rfc/issues/77 or some variant of it.

**Comment by joostjager** [comment]
That is a good point, definitely. I think that #77 with its polling mechanism would indeed cover it.
