### ISSUE TITLE
bech32-encoded QR codes are bigger than QR codes with normal URLs

### ISSUE THREAD

**Issue by fiatjaf** [btcontract/lnurl-rfc#15]
Here's a QR code for `https://charger.bigsun.xyz/lnurl-login?tag=login&k1=b58e7b599ac78aea4393a34f4250e3abbe31f9674ba28cf8db113de28de5efbe`:
![index](https://user-images.githubusercontent.com/1653275/67157382-944b7200-f301-11e9-8bdc-36bda60a2387.gif)

And now one for `LNURL1DP68GURN8GHJ7CMGV9EXWETJ9E3XJEMNW4HZU7RE0GHKCMN4WFKZ6MR0VA5KU0M5V9NN6MR0VA5KUFNTXY7KYDFCV5MKYDFE89SKXDECV9JKZDPN8YEKZVE5VC6RYDFSV5EKZCNZV5ENZE3EXCMNGCNPXGUXXE3CV33RZVFNV3JNYWRYV56K2ENZV5ZUKEYM`, the lnurl-bech32-encoded version of the above:
![index](https://user-images.githubusercontent.com/1653275/67157386-9b728000-f301-11e9-8f5c-5a3881d3c2b0.gif)

Apparently the uppercasing QR-reduction properties aren't so powerful as one would think initially.

**Comment by btcontract** [comment]
Well at least bech32 still provides a useful `lnurl` prefix.

**Comment by fiatjaf** [comment]
That's what I thought also.

**Comment by whitslack** [comment]
I'll just point out: if you use _uppercase_ for the hexadecimal `k1` value, then the optimal QR code is even more compact:

`https://charger.bigsun.xyz/lnurl-login?tag=login&k1=B58E7B599AC78AEA4393A34F4250E3ABBE31F9674BA28CF8DB113DE28DE5EFBE`  
<img width="196" height="196" alt="Image" src="https://github.com/user-attachments/assets/340e48d2-b416-4364-87b7-dbe14f507592" />  
That QR code contains only 793 data bits versus the 940 bits of the all-lowercase version.

If you also use uppercase for the URI scheme and the domain name, then you can get the QR code down to 739 data bits, but the resulting symbol is not any smaller for this particular URI.
