### ISSUE TITLE
lnurl-auth IP address

### ISSUE THREAD

**Issue by nerd2ninja** [btcontract/lnurl-rfc#153]
I'm trying to implement this via ruby on rails. For testing, I'd like to use my laptops internal IP address. The wallets I've used so far, seem to view IP addresses as invalid LNURLs

Is there a lnurl-auth wallet I can use for IP addresses in place of domain names for development purposes?

**Comment by fiatjaf** [comment]
No.

But you can try running https://github.com/fiatjaf/seed-auth locally or installing this extension: https://github.com/pseudozach/seedauthextension (it's available on Chrome and Firefox stores).

**Comment by nerd2ninja** [comment]
"Sites that you login with LNURL AUTH will show up here..."
But I have to login with the protocol that I'm trying to implement for it to work. I was hoping to catch a request sent from a wallet.

I'm going to try making an internal IP DNS resolver using bind9 on ubuntu.

No is the answer to my question so I'll be closing this issue now.
