### ISSUE TITLE
"image/png;base64" not marked as mandatory nor optional

### ISSUE THREAD

**Issue by raweber42** [btcontract/lnurl-rfc#258]
in [this](https://github.com/lnurl/luds/blob/luds/06.md#pay-to-static-qrnfclink) section in the `metadata` part, the `image/png;base64` field is neither marked as mandatory nor optional. Is this on purpose?

**Comment by hsjoberg** [comment]
Hmm, no looks like a mistake. It is optional

**Comment by hsjoberg** [comment]
Fixed in 901e3830e8def3cd2590de3e7e543db2c49313d8. Thanks
