### ISSUE TITLE
LUD-06 - What is "pr"

### ISSUE THREAD

**Issue by patrickReiis** [btcontract/lnurl-rfc#263]
[In the step 6](https://github.com/lnurl/luds/blob/luds/06.md#pay-to-static-qrnfclink), it's mentioned that `LN Service` takes the GET request and returns a JSON response in form of:  
```
{
    pr: string, // bech32-serialized lightning invoice
    routes: [] // an empty array
}
```

What does `pr` stands for? I tried imagining it or looking it up on the internet but I couldn't find it.

**Comment by hsjoberg** [comment]
Hi. It stands for Payment Request. A common term for BOLT11 invoices.

**Comment by patrickReiis** [comment]
Thank you very much!
