### ISSUE TITLE
What's the rationale for the 2-steps flow of LNURL-pay ?

### ISSUE THREAD

**Issue by dpad85** [btcontract/lnurl-rfc#28]
Hello,

Commit d9f902c9d99c465de24a6165ad9bf17d78d16a74 brought a significant change to the `lnurl-pay` flow: instead of having a single `GET` that would retrieve all the necessary data for the payment in one go, the client must now:

1. `GET` payment metadata from the server
2. Show meta to the user and wait for his input (spec mentions using a dialog)
3. `GET` the actual BOLT11 invoice

I could only find the following rationale for this change, in issue https://github.com/btcontract/lnurl-rfc/issues/9#issue-480148402:

> 1 is simpler and easier to implement as it involves less roundtrips but it doesn't allow for undefined-amount payments and it also leaks the customer privacy as he scans the QR code even if he didn't decide to pay.

Which does not make sense to me:
- Server can provide an amount-less invoice even with a single `GET` flow.
- The new flow still "leaks customer privacy" since the client **WILL** send a `GET` to some server as soon as the QR is scanned, even if that's only to retrieve some metadata.

Is there another rationale for this change? It seems to me that one of the key objective of LNURL-pay is to provide static invoices, that is, being able to generate a Lightning invoice from a fixed `URI`. Having a 2-steps flow breaks this, and makes the protocol harder to implement, so I may have missed something?

Sorry if this has already been discussed.

**Comment by btcontract** [comment]
Amount-less invoice is exactly an issue here as even when relayer-stealing possibility is eliminated by payment secret it's still not possible to prove an exact amount paid which may be an issue sometimes.

Also consider more creative `lnurl-pay` use cases, something like this one (not documented yet but chances are it will be):
![photo_2020-01-07_16-44-35](https://user-images.githubusercontent.com/9870980/71903637-32b2db00-316d-11ea-9ddd-fd28596d3d14.jpg)

Without two-step scheme it won't be possible to know which exact amount a user has chosen.

**Comment by fiatjaf** [comment]
The problem of amountless invoices is that they don't provide proof of amounts, so someone could buy a cookie for 10000 sat but since the invoice is amountless they will pay just 1 sat and get the payment proof and argue over the counter that they've paid -- or worse: if the `successAction` is of type `AES` they will have access to the secret code and automatically redeem their cookie or something like that event though they only paid a fraction of the value.

Amountless invoices used to be unsafe to send along routes, now that problem is being fixed with the new invoice secret, but still they aren't useful for anything besides donations.

**Comment by dpad85** [comment]
Amount-less invoices are not great I agree, quite useless for merchants and otherwise only useful for donations which is an edge case.

> Also consider more creative lnurl-pay use cases, something like this one (not documented yet but chances are it will be): 
> 
> Without two-step scheme it won't be possible to know which exact amount a user has chosen.

Thanks for the explanation it makes sense. We don't really want to support complex payment flows in Phoenix/Eclair Mobile, like in the screenshot example you've given, I'd prefer this to be handled by the merchant as much as possible. 

Would you consider making these (future) sophisticated use cases optional? For example, we could use the `tag` field to discriminate between the basic flow we have now, and more involved flows with complex UI (and maybe more `GET`s). That would allow the client wallet to gracefully fail an unsupported LNURL-pay use-case.

**Comment by btcontract** [comment]
> Would you consider making these (future) sophisticated use cases optional?

Yes, so far we've been good at not breaking stuff and we intend to keep it this way. Choice in particular may not need a new tag and be fully backwards-compatible (by setting `maxSendable` = `minSendable` = first choice value, accompanied by `choice` details field which non-supporting wallet will disregard).

**Comment by dpad85** [comment]
Great, thank you. Closing this issue.
