### ISSUE TITLE
Why bech32? .well-known URLs and wallet-initiated interactions.

### ISSUE THREAD

**Issue by fiatjaf** [btcontract/lnurl-rfc#3]
Why can't the `lnurl` have just query strings as normal URLs?

What about using `/.well-known/whatever` endpoints? Aside from handling the cases described in https://github.com/btcontract/lnurl-rfc/blob/61071a18453c3e8a99f65c1db94fdd1c2f2e1247/spec.md, LN services could have `/.well-known/lnurl:withdraw` URLs, for example, that would allow automatic withdrawing at the request of the wallet, without user interaction (so a wallet could programmatically withdraw funds from a custodial site every day or week, for example).

Other interesting cases are `/.well-known/ln:deposit` for depositing money on websites from the wallet itself, without the user even having to scan a QR code or deal with an invoice. This could also be used by individuals who want to be paid and have a webserver (or a variant, `/.well-known/ln:pay`).

All these cases are doable with the `lnurl` scheme described, I'm just suggesting `.well-known` because it is a (sort of) standard.

**Comment by btcontract** [comment]
It's bech32-encoded to adhere to general standard (btc addresses, ln invoices) and to enable QR optimization where all the letters can be upper case, plus this provides error detection.

The point of `lnurl` is that service can attach a user-specific token as query parameter so in case of withdrawal for example a service knows who is authorized to do this. Don't think this is possible with static endpoint.
