### ISSUE TITLE
Allow HTTP URLs for lnurl-pay

### ISSUE THREAD

**Issue by fiatjaf** [btcontract/lnurl-rfc#32]
While requiring HTTPS URLs for lnurl-pay is fine for any service offered over the internet, it sometimes make it very hard for small people who don't know or are unable to be running stuff on their own domain to accept payments in that way.

Without HTTP, it would be possible for people to use lnurl-pay inside LANs, through IPv6-powered home computers, or even to run lnurl-pay endpoints from their own phones, so easier for local merchants individuals to do this without relying on trusted third-parties.

Since lnurl-pay already relies on a final invoice issued by a Lightning server and that invoice is signed, one could optionally opt in to the HTTP verification by appending a `?pk=<lightning-node-pubkey>` query string param to the initial URL that is shared with the payer.

Then, if the communication was done through HTTP and not HTTPS, the wallet would check if the initial `pk` matches the public key that signed the final invoice received as an extra check.

**Comment by btcontract** [comment]
is this about the need to purchase a certificate? if yes than one option would be unsigned certificates (BLW supports those already but that could be explicitly stated in spec) and another one is something like letsencrypt.

**Comment by fiatjaf** [comment]
Aren't self-signed certificates the same as not having a certificate?

LetsEncrypt works, but, as I said, it's too much work. Apparently a large group of people are ok with getting some piece of software prebuilt by others and running it. That could work for a local merchant trying to accept lnurl-pay payments, but the domain requirement breaks that, because it's not just running some software now, now they need sysadmin skills. They have to buy a domain, mess up with DNS records, then probably have a dedicated machine running nginx or something like that with a LetsEncrypt daemon renewing certificates every day and all that is a big barrier.

Being able to serve stuff directly from an IP would be nice. Self-signed certificates would work, I guess, but I'm afraid they are not safe.

Anyway, this is just an idea, I'm not in a hurry. Maybe there are better ways.

**Comment by btcontract** [comment]
> Self-signed certificates would work, I guess, but I'm afraid they are not safe.

They are not as explained here https://security.stackexchange.com/questions/184969/how-mitm-attack-got-performed-on-self-signed-certificate-while-private-keys-is-g but they are easy to set up and still provide better security if client knows what to expect.

**Comment by btcontract** [comment]
Sort of resolved in https://github.com/btcontract/lnurl-rfc/pull/34
