### ISSUE TITLE
LAPPURL - Communication between apps via 'lightning:' URL Scheme

### ISSUE THREAD

**Issue by jackeveritt** [btcontract/lnurl-rfc#33]
## LAPPURL

The LNURL flow describes that after the LNURL is decoded, a request is made to the LN SERVICE to attain the full transaction data in JSON format.  The reason for this step is encoding transaction JSON into the LNURL directly would make it too large and impractical for QR codes.

However, when two apps communicate via the `lightning:` URL Scheme, size limitations are not relevant. For App to App communication, we could encode the transaction JSON in a LAPPURL, meaning the GET request to the service is no longer required.

This optimisation is specifically for the use case of app to app communications, intended to be hidden from the user.  This change would have the following advantages to developers of Lapps who plan to use the `lightning:` URL Scheme **only** in their product;

1) Less burden on the developer to maintain 'state' of their LNURLs in their `LN SERVICE`.
2) Less customer support requests - if the `LN SERVICE` fails to deliver the transaction JSON for whatever reason, this is handled differently by different wallets.
3) Faster transactions - If the wallet opens a LAPPURL they can immediately show the transaction interface instead of waiting for a response from an `LN_SERVICE`
4) For wallet developers, there are less steps which require error handling

Here is an example of how a LAPPURL could be used for withdrawals

### Withdrawing funds from a Lapp

**Lapp to Wallet service interaction flow:**

1. User taps a withdrawal button in `LN APP`, which creates a LAPPURL - a bech32 encoded json:

	```
	{
		callback: String, // the URL which LN APP has defined as it's LN SERVICE, would accept a withdrawal Lightning invoice as query parameter
		k1: String, // random or non-random string to identify the user's LN WALLET when using the callback URL
		maxWithdrawable: MilliSatoshi, // max withdrawable amount for a given user on LN SERVICE
		defaultDescription: String, // A default withdrawal invoice description
		minWithdrawable: MilliSatoshi // An optional field, defaults to 1 MilliSatoshi if not present, can not be less than 1 or more than `maxWithdrawable`
		tag: "withdrawRequest" // type of LAPPURL
	}
	```

2. `LN APP` opens `LN WALLET` with `lightning:LAPPURL..`  and `LN WALLET` decodes LAPPURL to retrieve the JSON.
3. `LN WALLET` Displays a withdraw dialog where user can specify an exact sum to be withdrawn which would be bounded by: 
	
	```
	max can receive = min(maxWithdrawable, local estimation of how much can be routed into wallet)
	min can receive = max(minWithdrawable, local minimal value allowed by wallet)
	```
5. Once accepted by the user, `LN WALLET` sends an HTTPS GET to `LN SERVICE` in the form of 
	
	```
	<callback>?k1=<k1>&pr=<lightning invoice, ...>
	```
	
6. `LN SERVICE` sends a `{"status":"OK"}` or `{"status":"ERROR", "reason":"error details..."}` JSON response and then attempts to pay the invoices asynchronously.
7. `LN WALLET` awaits for incoming payment if response was successful.

**Comment by btcontract** [comment]
I think we can make this backwards compatible using existing tools rather than introducing new prefix.

Initial LNURL will be the same:

`lightning:LNURL<encoded data>`.

But will encode this:

`https://site.com/withdraw/whatever ? tag = fastwithdraw & json = {"callback":"https://site.com/withdraw/user1/proceed","k1":"k1","maxWithdrawable":100,"defaultDescription":"A default withdrawal invoice description","minWithdrawable":100,"tag":"withdrawRequest"}`

According to spec: 

> If tag query parameter is present then this LNURL has a special meaning, further actions will be based on tag parameter value.
> Otherwise an HTTPS GET request should be issued which must return a Json object containing a tag field, further actions will be based on tag field value.

This is exactly our case where bech32 encoded url should not be called right away but something else must be done (in this case: provided json should be used immediately). 

Older wallets will ignore tag part and will call an obtained URL to either get the same Json or error message (`{"status":"ERROR", "reason":"update your wallet"}` for example).

**Comment by jackeveritt** [comment]
@btcontract Yes you solution would be much better.

**Comment by baebb** [comment]
@btcontract 

Putting JSON objects in urls not as url parameters is pretty messy and generally avoided. 

The example json you posted above will first need to be encoded as a URL string:
`%7B%22callback%22%3A%22https%3A%2F%2Fsite.com%2Fwithdraw%2Fuser1%2Fproceed%22%2C%22k1%22%3A%22k1%22%2C%22maxWithdrawable%22%3A100%2C%22defaultDescription%22%3A%22A%20default%20withdrawal%20invoice%20description%22%2C%22minWithdrawable%22%3A100%2C%22tag%22%3A%22withdrawRequest%22%7D`

...then we encode that as a bech32 string with the callback url:
`LNURLNB2HI4DTHIXS643JORSS4Y3PNUXXO2LUNBSHEYLXF53WQYLUMV3GK4R7ORQWOPLGMFZXI53JORUGI4TBO4TGU43PNYQD2JJXIISTEMTDMFWGYYTBMNVSKMRSEUZUCJJSGJUHI5DQOMSTGQJFGJDCKMSGONUXIZJOMNXW2JJSIZ3WS5DIMRZGC5ZFGJDHK43FOIYSKMSGOBZG6Y3FMVSCKMRSEUZEGJJSGJVTCJJSGISTGQJFGIZGWMJFGIZCKMSDEUZDE3LBPBLWS5DIMRZGC53BMJWGKJJSGISTGQJRGAYCKMSDEUZDEZDFMZQXK3DUIRSXGY3SNFYHI2LPNYSTEMRFGNASKMRSIESTEMDEMVTGC5LMOQSTEMDXNF2GQZDSMF3WC3BFGIYGS3TWN5UWGZJFGIYGIZLTMNZGS4DUNFXW4JJSGISTEQZFGIZG22LOK5UXI2DEOJQXOYLCNRSSKMRSEUZUCMJQGASTEQZFGIZHIYLHEUZDEJJTIESTEMTXNF2GQZDSMF3VEZLROVSXG5BFGIZCKN2E`

...which will require the QR to be quite detailed, creating recognition issues for low-res camera phones:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/8374514/74605147-9e8f4880-5108-11ea-89ee-7f130bf3919e.png">

**Comment by jackeveritt** [comment]
@baebb  The intention of this special type of LNURL is that you would not use it for a QR code. Only to send to another app.

The json could be bech32 encoded?

`https://site.com/withdraw/whatever ? tag = fastwithdraw & json =10DSK6MM4DE6R5GPS9SS82UM9WFYKGW3QV5ENX5M9V4NRYVMXG5ENYVFJX3NXGUTHXFAZCGRDV4KK7WJ5FP8YG53QGAQ5632NYPG9YJ26G5KZQCMPD3KXYCTRDVAXSAR5WPEN5TE0W4EJ6CM9DE68YCTVXYKHG6RWV3EZ6MRWW4EXCTNRD3HH2ERXW4HXXARFDAH8XTNWV46Z7MRWW4EXCTMKXYHHW6T5DPJ8YCTH9SSXXMMDWPKX2ARFDAHYXCTVD33XZCMT8F58GARSWVAZ7TM5DPHXGU3WVASK6ETN9ASHQ6F0WCCJ7MRWW4EXCLFLWY7NJEFC8YUXVWF5X93RGVPSVEJRXDE3V56NWVMRXQUKGWT989JXZV3SXFNRYCFSV5ERZCFSXCCRGVPCXUEKVWF5VENXXWFC8QCRSE3KXS4LJ7UU`

**Comment by btcontract** [comment]
@baebb it's a bit messy but not THAT bad:
- this whole use case is for in-app withdrawal only so QR code won't be shown at any point.
- Json is irrelevant for URL so we don't need to care about encoding.

Perhaps to make it more clear tag should be not `fastwithdraw` but something like `appwithdraw`.

**Comment by jackeveritt** [comment]
Yeah I like `appwithdraw`. Optional, if the wallet implements it they can skip the whole first GET step as they already have the data.

**Comment by fiatjaf** [comment]
Why not `https://fallbackURL?tag=withdrawRequest&minWithdrawable=1&maxWithdrawable=10&defaultDescription=xyz&callback=callback` instead of JSON? The same wallet could handle `withdrawRequest` either get the parameters from the query string if they are available or call the URL if they're not.

**Comment by baebb** [comment]
@jackeveritt the JSON needs to be formatted to a URL string first, then the whole URL needs to be bech32'ed. See my steps. 

@btcontract @fiatjaf 

If this new LNURL type is implemented it will enable users to copy expired/redeemed the new type LNURLs, which will fail, but generate a LN invoice in the process. 

It feels like we're making something that works already into something more fragile and complicated for wallet maintainers. They will need to refactor their code to handle both old and new types of LNURL-withdraw. They still have bugs in their v1 implementations. 

If we want to do this change, I think we should start planning for a LNURL v2 spec instead of duct-taping things into v1.

**Comment by btcontract** [comment]
@fiatjaf this one seems to be the best.

@baebb 
> If this new LNURL type is implemented it will enable users to copy expired/redeemed the new type LNURLs, which will fail, but generate a LN invoice in the process.

Yes, but this does not sound like a big deal to me. Also this is intended to be used in apps where copy/pasting should be hidden.

**Comment by jackeveritt** [comment]
@baebb 
> If this new LNURL type is implemented it will enable users to copy expired/redeemed the new type LNURLs, which will fail, but generate a LN invoice in the process.

In my use case (mobile game), I will generate and call this type of LNURL with 'lightning:' all at the same time.  So the transaction should not fail unless I put a 'timeout' on the transaction process as a whole.  This will be checked by step 5, of the original withdrawl spec and return an error to the wallet if the LNURL has timed out or expired.

The user will never see or in normal circumstances have access to it.

**Comment by jackeveritt** [comment]
Another consideration (although small) is that not requiring the first GET request reduces server costs for the `LN SERVICE`
