### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Falsen** [btcontract/lnurl-rfc#5]
I am trying to implement this but without luck. Found this JS implementation:
https://github.com/sipa/bech32/blob/master/ref/javascript/bech32.js
but it doesn't seem to work. I am comparing to the bech32 library and I am not receiving the same output with the same inputs.

Looking at the bottom off this python file: https://github.com/fiatjaf/bech32/blob/master/bech32/__init__.py, seems like I need to convert the data into a 5-bit array? Which isn't done by bech32.js

Found this code that should be able to convert to a 5-bit array... https://github.com/bitcoincashjs/cashaddrjs/blob/master/src/convertBits.js

It's all a mess and I'm not sure I can do anything on my own, I am not very familiar with bech32 and bit-operations in general.

I am not sure how your example works (https://gist.github.com/btcontract/a917d9b8b9b8fd53a87a81528e1274c5) because I am using the same library (I think). Installed with `npm install bech32`

Following the code... This line gives:
`bech32.encode('LNURL', 'https://satoshis.games/withdrawal/confirmation?q=')
`

`
'lnurl1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqesxn47'
`

Help appreciated!

**Comment by btcontract** [comment]
Try https://github.com/bitcoinjs/bech32 and 

```js
let words = bech32.toWords(Buffer.from('https://localhost:3322/withdraw/confirmation?q=', 'utf8'))
bech32.encode('lnurl', words)
```

**Comment by Falsen** [comment]
Thank you very much! It works :)
Implemented it on http://lightningflip.xyz

**Comment by btcontract** [comment]
nice!
