### ISSUE TITLE
Unspecified response in case of invalid request

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnurl-rfc#6]
The specification doesn't describe what response should be at step 2 when there's an error - e.g. the secret is invalid. Should there be specific JSON body or just HTTP error? Which HTTP error?

**Comment by btcontract** [comment]
Currently the only client implementation (BLW) awaits for a valid Json as a response there and shows a raw error dump if anything goes wrong (Json could not be parsed, non-200 status code etc). Perhaps we can use a scheme similar to .6 there (`{"status":"ERROR", "reason":"error details..."}`), what do you think?

**Comment by btcontract** [comment]
I've updated both BLW and spec according to my above proposal for now.

**Comment by Kixunil** [comment]
Yeah, that works for me well. I've updated [lnch-vekslak](https://github.com/Kixunil/lnch-vekslak).
