### ISSUE TITLE
lnurl-pay protocol

### ISSUE THREAD

**Issue by fiatjaf** [btcontract/lnurl-rfc#9]
A protocol like this could be the solution for all services and websites that want to show a static QR code for payments (like a static site or a site not directly connected to an LN node), a QR code that could be *printed on paper* and so on -- while at the same time allowing for payment/user identification without loss of privacy (by the optional usage of per-service [`linkingKey`s](https://github.com/btcontract/lnurl-rfc/blob/master/spec.md#2-lnurl-login)).

## Example use cases:

1. Donation webpages and other web-scenarios where one wants variable-amount payments;
2. Restaurant menus;
3. Simplification of setups where a webpage wants to accept payments (for simple, more "manual", things like selling a t-shirt) while the LN node responsible for that is running on a different computer;
4. Pricing tags in market shelves (I'm just imagining a new self-checkout experience where the customer would pay at the time they would pick up the product from the shelf instead of paying everything at the end);
5. Bike/scooter-sharing services and other fancy modern indie stuff;
6. Other noveau use-cases like those powered by [WeChat and Alipay stuff on China](https://www.youtube.com/watch?v=75AXINUL47g);

## Spec suggestion

Two ideas of how this could be done come to my mind:

1. _
  a. As the wallet scans a QR code it identifies the `?tag=pay&k1=<challenge>` in the lnurl and immediately calls the URL with the signed challenge;
  b. Now the service knows who is willing to pay and returns `pr` (an invoice) along with `metadata`;
  c. The wallet displays a "Pay" screen to the user enhanced with the received metadata;
  d. The user decides to pay, then the service already knows who paid that and reacts accordingly.
2. _
  a. As the wallet scans a QR code it first calls the URL;
  b. From the service response it gets `tag: "pay"` plus `callback`, `k1`, `metadata` and pricing information somehow (a fixed price or min/max prices?);
  c. Then the service displays the enhanced "Pay" screen with room for the user to decide the amount if that is not fixed;
  d. After the user clicking "confirm" the wallet sends the chosen amount to `callback`, plus the `k1` signed with the user's `linkingKey`, then gets a `pr` (invoice) back;
  e. The wallet automatically pays the invoice if it matches the amount and metadata.

The spec **1** is simpler and easier to implement as it involves less roundtrips but it doesn't allow for undefined-amount payments and it also leaks the customer privacy as he scans the QR code even if he didn't decide to pay.

### On the metadata returned by the service

The `metadata` field could be a string, a JSON object, raw HTML or who-knows-what, but the wallet will have to display it to the user somehow. Perhaps a good idea would be to do like emails do and return the metadata in all available mimetypes the service supports (a raw string should be mandatory) so the wallet can choose the one it wants and display.

The metadata could also be hashed into the invoice description (or in the `descriptionHash` field if that's still a living thing). This is useful for accountability between the parties.

**Comment by arcbtc** [comment]
Came here to write the same thing, me and my friend George explored this last year https://youtu.be/TTpEpk5LJ4E?t=1016
Static QRs would also allow money streaming for a service. LNURL has renewed my hope that this could happen soon

**Comment by HamishMacEwan** [comment]
This portion, `identifies the ?tag=pay&k1=<challenge> in the lnurl and immediately calls the URL with the signed challenge;` could be implemented using the work done here:

https://github.com/bitid/bitid/blob/master/BIP_draft.md

The client side of this is currently implemented in the Mycelium wallet and bitid.nz is a link to the demo hosted at Heroku.

**Comment by btcontract** [comment]
@HamishMacEwan Lnurl has its own signing method defined in a spec.

**Comment by fiatjaf** [comment]
from Anton Kovalenko:

> Re lnurl-pay: I propose splitting lnurl-pay into steps like this:
> 
> First step (when the amount is not known): client does HTTP GET as per the old spec, answer contains minSendable, maxSendable, description: String, tag: "specifyAmount", and optional nextUrl. As there's no invoice yet, hashed metadata aren't used in this step, but a plain-text description can be presented (like "donate to @fiatjaf", or "top-up phone +79163453402").
> 
> Client asks user for the amount, then it GETs nextUrl (if present) or original URL, with "msat" parameter appending, specifying the amount.
> 
> Server, when receiving msat parameter, answers according to the original spec, with payment request and hashed metadata, but without minSendable and maxSendable. Client should ask user to confirm payment, showing URL domain and text/plain metadata (which could be more specific than initial description, like "top-up phone +79163453402 with 5 USD")
> 
> Why nextUrl? This way, server, if needed, can link two steps together (e.g. provide exchange rate in "description" during the first step, and guarantee the same rate for actual operation if user proceeds to the second step in time).
> 
> For simple donation URLs, ?tag=pay and ?tag=pay&msat=100000 can be both valid lnurls (server would do either first or second step depending on msat presence, and reGET from the same URL with msat when user specifies amount).
> 
> As long as there's an unhashed description, TLS certificate validity should be checked by client. (LN node-level signing & verification could be used for "description", but I don't actively propose it because LND sucks in verification)

**Comment by fiatjaf** [comment]
I'm beginning to think there could be thousands of different useful features on lnurl-pay, like

* redirecting to a webpage URL after paying
* choosing options in the lnurl-pay menu that get sent to the server before the wallet gets the invoice string
* ways to link multiple payments with a single identity, either only for a session or for the entire life of the wallet

But it doesn't make sense to implement all that crap at once before the protocol has seen any real-world usage, so there should be a way to implement the `metadata` field such that other stuff could be added later. I don't know if it should be called `metadata` anymore, as I think having rich text metadata besides basic text (and some buttons maybe, someday?) will be too much. Maybe a binary field with a sequence of TLVs would be the best thing as it could be easily extendable in the future.

**Comment by fiatjaf** [comment]
I'm thinking that this could enable somewhat-standardized interactive interfaces for lightning wallets to interact with services. Like Telegram or Slack bots, for example: there's a limited set of interactions the client would support (like simple buttons and simple input fields) and the service would send a description of what it wants the client to display. The client displays that, gather input and sends the data back to the service, which then sends an invoice and the client pays it.

The initial implementation of the standard of interaction components could be just `show text, ask for amount`, but later it could be `show list of pizza buttons with prices, user clicks at the pizza he wants`, then later `show whatever, but after the payment is complete redirect to https://service.com/thank-you`.
